# Generated by Django 5.2.2 on 2025-06-10 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_name', models.CharField(max_length=50)),
                ('car_version', models.CharField(max_length=50)),
                ('car_year', models.CharField(max_length=4)),
                ('car_brand', models.CharField(choices=[('Ferrari', 'Ferrari'), ('Lamborghini', 'Lamborghini'), ('koenigsegg', 'koenigsegg'), ('Bugatti', 'Bugatti'), ('McLaren', 'McLaren'), ('BMW', 'BMW'), ('Mercedes', 'Mercedes')], max_length=15)),
                ('car_status', models.BooleanField(default=True)),
                ('car_photo', models.ImageField(upload_to='photos')),
            ],
        ),
    ]
