# Generated by Django 5.2.2 on 2025-06-12 20:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tags_choices_save', models.CharField(choices=[('HYPERCAR', 'HYPERCAR'), ('SUPERCAR', 'SUPERCAR'), ('SPORTCAR', 'SPORTCAR'), ('LUXURYCAR', 'LUXURYCAR')], default='HYPERCAR', max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Cardata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier', models.PositiveIntegerField()),
                ('description', models.TextField()),
                ('photo_or_video', models.FileField(upload_to='photo_or_video')),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.cars')),
                ('tags_choices_save', models.ManyToManyField(to='cars.tags')),
            ],
        ),
    ]
