# Generated by Django 5.2.2 on 2025-06-13 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_tags_cardata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cars',
            name='car_brand',
            field=models.CharField(choices=[('Ferrari', 'Ferrari'), ('Lamborghini', 'Lamborghini'), ('koenigsegg', 'koenigsegg'), ('Bugatti', 'Bugatti'), ('McLaren', 'McLaren'), ('BMW', 'BMW'), ('Mercedes', 'Mercedes'), ('Audi', 'Audi'), ('Dodge', 'Dodge'), ('Ford', 'Ford'), ('Chevrolet', 'Chevrolet'), ('Others', 'Others')], max_length=15),
        ),
    ]
