# Generated by Django 5.2.2 on 2025-06-17 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_alter_tags_tags_choices_save'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tags',
            name='tags_choices_save',
            field=models.CharField(choices=[('HYPER CAR', 'HYPER CAR'), ('SUPER CAR', 'SUPER CAR'), ('SPORT CAR', 'SPORT CAR'), ('MUSCLE CAR', 'MUSCLE AR'), ('LUXURY CAR', 'LUXURY CAR'), ('COLLECTIBLE CAR', 'COLLECTIBLE CAR'), ('RACE CAR', 'RACE CAR'), ('COMMON CAR', 'COMMON CAR'), ('OTHERS', 'OTHERS')], max_length=20),
        ),
    ]
