# Generated by Django 5.2.2 on 2025-06-18 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0008_tier_remove_cardata_tags_choices_save_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cars',
            name='car_status',
        ),
    ]
