# Generated by Django 5.2.2 on 2025-06-18 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0009_remove_cars_car_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cardata',
            name='photo_or_video',
        ),
        migrations.AddField(
            model_name='cardata',
            name='car_file',
            field=models.FileField(null=True, upload_to='car_file'),
        ),
    ]
