# Generated by Django 5.2.2 on 2025-06-18 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0010_remove_cardata_photo_or_video_cardata_car_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardata',
            name='car_tier',
            field=models.CharField(blank=True, choices=[('S+', 'S+'), ('S', 'S'), ('A+', 'A+'), ('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F')], max_length=10, null=True),
        ),
    ]
