# Generated by Django 5.2.2 on 2025-06-18 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0012_alter_tier_tiers_choices_save'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardata',
            name='car_power',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='cardata',
            name='car_torque',
            field=models.FloatField(null=True),
        ),
    ]
