# Generated by Django 5.2.2 on 2025-06-18 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0013_alter_cardata_car_power_alter_cardata_car_torque'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardata',
            name='car_power',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='cardata',
            name='car_torque',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
