# Generated by Django 5.2.2 on 2025-06-18 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0014_alter_cardata_car_power_alter_cardata_car_torque'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardata',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
