# Generated by Django 5.2.2 on 2025-07-22 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0015_alter_cardata_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_choices_save', models.CharField(choices=[('White', 'White'), ('Black', 'Black'), ('Silver', 'Silver'), ('Red', 'Red'), ('Light Blue', 'Light Blue'), ('Blue', 'Blue'), ('Navy Blue', 'Navy Blue'), ('Purple', 'Purple'), ('Pink', 'Pink'), ('Violet', 'Violet'), ('Orange', 'Orange'), ('Green', 'Green'), ('Gray', 'Gray'), ('Gold', 'Gold'), ('Wrapped', 'Wrapped'), ('Exposed Carbon Fiber', 'Exposed Carbon Fiber'), ('Others', 'Others')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_choices_save', models.CharField(choices=[('USA', 'USA'), ('Brazil', 'Brazil'), ('Canada', 'Canada'), ('UK', 'UK'), ('France', 'France'), ('Italy', 'Italy'), ('Germany', 'Germany'), ('Japan', 'Japan'), ('China', 'China'), ('Australia', 'Australia'), ('Others', 'Others')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='WheelSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wheel_size_choices_save', models.CharField(choices=[('15"', '15"'), ('16"', '16"'), ('17"', '17"'), ('18"', '18"'), ('19"', '19"'), ('20"', '20"'), ('21"', '21"'), ('22"', '22"'), ('23"', '23"'), ('24"', '24"'), ('25"', '25"'), ('26"', '26"'), ('27"', '27"'), ('28"', '28"'), ('29"', '29"'), ('30"', '30"'), ('Others', 'Others')], max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='cardata',
            name='car_color',
            field=models.CharField(blank=True, choices=[('White', 'White'), ('Black', 'Black'), ('Silver', 'Silver'), ('Red', 'Red'), ('Light Blue', 'Light Blue'), ('Blue', 'Blue'), ('Navy Blue', 'Navy Blue'), ('Purple', 'Purple'), ('Pink', 'Pink'), ('Violet', 'Violet'), ('Orange', 'Orange'), ('Green', 'Green'), ('Gray', 'Gray'), ('Gold', 'Gold'), ('Wrapped', 'Wrapped'), ('Exposed Carbon Fiber', 'Exposed Carbon Fiber'), ('Others', 'Others')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cardata',
            name='car_country',
            field=models.CharField(blank=True, choices=[('USA', 'USA'), ('Brazil', 'Brazil'), ('Canada', 'Canada'), ('UK', 'UK'), ('France', 'France'), ('Italy', 'Italy'), ('Germany', 'Germany'), ('Japan', 'Japan'), ('China', 'China'), ('Australia', 'Australia'), ('Others', 'Others')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cardata',
            name='car_wheel_size',
            field=models.CharField(blank=True, choices=[('15"', '15"'), ('16"', '16"'), ('17"', '17"'), ('18"', '18"'), ('19"', '19"'), ('20"', '20"'), ('21"', '21"'), ('22"', '22"'), ('23"', '23"'), ('24"', '24"'), ('25"', '25"'), ('26"', '26"'), ('27"', '27"'), ('28"', '28"'), ('29"', '29"'), ('30"', '30"'), ('Others', 'Others')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cardata',
            name='car_tag',
            field=models.CharField(blank=True, choices=[('HYPER CAR', 'HYPER CAR'), ('SUPER CAR', 'SUPER CAR'), ('SPORT CAR', 'SPORT CAR'), ('MUSCLE CAR', 'MUSCLE CAR'), ('LUXURY CAR', 'LUXURY CAR'), ('SUV', 'SUV'), ('PICKUP', 'PICKUP'), ('EV', 'EV'), ('COLLECTIBLE CAR', 'COLLECTIBLE CAR'), ('RACE CAR', 'RACE CAR'), ('COMMON CAR', 'COMMON CAR'), ('OTHERS', 'OTHERS')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='cars',
            name='car_brand',
            field=models.CharField(choices=[('Ferrari', 'Ferrari'), ('Lamborghini', 'Lamborghini'), ('koenigsegg', 'koenigsegg'), ('Bugatti', 'Bugatti'), ('McLaren', 'McLaren'), ('BMW', 'BMW'), ('Mercedes', 'Mercedes'), ('Audi', 'Audi'), ('Dodge', 'Dodge'), ('Ford', 'Ford'), ('Chevrolet', 'Chevrolet'), ('Tesla', 'Tesla'), ('BYD', 'BYD'), ('Others', 'Others')], max_length=15),
        ),
        migrations.AlterField(
            model_name='tags',
            name='tags_choices_save',
            field=models.CharField(choices=[('HYPER CAR', 'HYPER CAR'), ('SUPER CAR', 'SUPER CAR'), ('SPORT CAR', 'SPORT CAR'), ('MUSCLE CAR', 'MUSCLE CAR'), ('LUXURY CAR', 'LUXURY CAR'), ('SUV', 'SUV'), ('PICKUP', 'PICKUP'), ('EV', 'EV'), ('COLLECTIBLE CAR', 'COLLECTIBLE CAR'), ('RACE CAR', 'RACE CAR'), ('COMMON CAR', 'COMMON CAR'), ('OTHERS', 'OTHERS')], max_length=20),
        ),
    ]
