# Generated by Django 5.2.2 on 2025-07-22 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0016_color_country_wheelsize_cardata_car_color_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cardata',
            old_name='car_wheel_size',
            new_name='car_wheel_size_back',
        ),
        migrations.AddField(
            model_name='cardata',
            name='car_wheel_size_front',
            field=models.CharField(blank=True, choices=[('15"', '15"'), ('16"', '16"'), ('17"', '17"'), ('18"', '18"'), ('19"', '19"'), ('20"', '20"'), ('21"', '21"'), ('22"', '22"'), ('23"', '23"'), ('24"', '24"'), ('25"', '25"'), ('26"', '26"'), ('27"', '27"'), ('28"', '28"'), ('29"', '29"'), ('30"', '30"'), ('Others', 'Others')], max_length=100, null=True),
        ),
    ]
