# Generated by Django 5.2.2 on 2025-07-22 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0017_rename_car_wheel_size_cardata_car_wheel_size_back_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cars',
            name='car_brand',
            field=models.CharField(choices=[('Ferrari', 'Ferrari'), ('Lamborghini', 'Lamborghini'), ('koenigsegg', 'koenigsegg'), ('Bugatti', 'Bugatti'), ('McLaren', 'McLaren'), ('Rolls-Royce', 'Rolls-Royce'), ('Bentley', 'Bentley'), ('BMW', 'BMW'), ('Mercedes', 'Mercedes'), ('Audi', 'Audi'), ('Dodge', 'Dodge'), ('Ford', 'Ford'), ('Chevrolet', 'Chevrolet'), ('Tesla', 'Tesla'), ('BYD', 'BYD'), ('Others', 'Others')], max_length=15),
        ),
    ]
