# Generated by Django 5.2.2 on 2025-07-24 17:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0020_newuser_user_age_day_newuser_user_age_month_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newuser',
            name='user_phone',
            field=models.CharField(blank=True, help_text='Format: +55011000000000', max_length=15, null=True, validators=[django.core.validators.RegexValidator(message='Phone number must be in the format: +55011000000000', regex='^\\+55\\d{12}$')]),
        ),
    ]
