# Generated by Django 5.2.2 on 2025-07-24 17:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0021_alter_newuser_user_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newuser',
            name='user_nickname',
            field=models.CharField(blank=True, help_text='5-15 characters. Only letters and numbers. No special characters.', max_length=15, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Nickname must be 5-15 characters long and contain only letters and numbers.', regex='^[a-zA-Z0-9]{5,15}$')]),
        ),
    ]
