# Generated by Django 5.2.2 on 2025-07-26 17:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0022_alter_newuser_user_nickname'),
    ]

    operations = [
        migrations.AddField(
            model_name='cars',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cars.newuser'),
        ),
    ]
