# Generated by Django 5.2.2 on 2025-08-01 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0024_newuser_reset_token'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Color',
        ),
        migrations.DeleteModel(
            name='Country',
        ),
        migrations.DeleteModel(
            name='Tags',
        ),
        migrations.DeleteModel(
            name='Tier',
        ),
        migrations.DeleteModel(
            name='WheelSize',
        ),
    ]
